apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-container
        image: qa-docker-nexus.mtnsat.io/dockerrepo/nodejs-app:6
        ports:
        - containerPort: 8087        
      imagePullSecrets:
      - name: regcred        
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  labels:
    app: nodejs-svc
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
    targetPort: 8087
    protocol: TCP
  #nodePort: 30001
  selector:
    app: nodejs-app
